/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import projecte.Projecte;
import metodes.GUI_UF3;
import projecte.Dj;
import finestrabenvinguda.finestrabenvinguda;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static metodes.GUI_UF3.carregaTaula;



/**
 *
 * @author alumne
 */
public class GUI extends javax.swing.JFrame {
    //carreugem fitxer de dades
    private static File fitxer = new File("dj.db");
    //segons el boolea escollit mostrem el seguent missatge (encontes de true false)
    private static final String MASCULI="Masculí";
    private static final String FEMENI="Femení";

    
    /**
     * Creates new form GUI
     */
    //pasem valor -1 per tal de si tenim alguna fila seleccionada
    private static int filaSel=-1;
    private int primeraCasellaBuida=-1;
    
    /**
     * Inicialitzem classe procipal de el nostre projecte
     */
    
    public GUI() {
        
        //Acontinuacio iniciem les intefifices grafiques
        //del nostre projecte.
        initComponents();
        inicialitzaComponents();
                
                //modifiquem els colors de la taula per tal que sino tinguem imatge de fons canviar el color
                this.getContentPane().setBackground(Color.black);
                taula.setBackground(Color.white);

        //seleccionem per defecte el boolea en true
        opcioMasculi.setSelected(true);
    }
   // private void ventanillaBenvinguda(){
    
   // }
    
    /**
     * Inicialitzem components del projecte
     */
    private void inicialitzaComponents(){
        
        //atraves de la variable seguent mostrem si en el borrat tenim una casella buida per omplir
        primeraCasellaBuida=Projecte.inicialitzarVariables();
        
        //carreguem les opcions que pasarem per la taula
        GUI_UF3.carregaTaula(new String[]{"Fila","Nom", "Lloc","Naixement","Sexe","Diners"}, 
                transformaDades(Projecte.getArray())
                , taula);
    
    }
    /**
     * Transformem en nostre array en una matriu
     * 
     * @param dades array que conté les dades a transformar
     * @return una matriu d'objectes que conté les dades que ens interessen
     */
    public static Object[][] transformaDades(Dj[] dades){
        Object[][] resultat=new Object[dades.length][6];
        //Variable per comptar el número de dj en dades que hi ha a l'array de dades
        int omplits=0;
        
        //pasem la dedes inserides per saber,sino el tenim omplit
        for (int i = 0; i < dades.length; i++) {
            if(dades[i].isOmplit()){
                resultat[omplits][0]=i;
                resultat[omplits][1]=dades[i].getNom();
                resultat[omplits][2]=dades[i].getLloc();
                resultat[omplits][3]=dades[i].getNaixement();
                resultat[omplits][4]=dades[i].isHome();
                //modiffiquem per tal de mostrar masculi o femeni en cas de ser el boolea true o false
                if(dades[i].isHome())
                   resultat[omplits][4]=MASCULI;
                   
               else resultat[omplits][4]=FEMENI;

                resultat[omplits][5]=dades[i].getDiners();
                omplits++;
            }
        }
        //Retornem només els dj plens
        return Arrays.copyOf(resultat,omplits);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new javax.swing.JTable();
        casellaNom = new javax.swing.JTextField();
        casellaLloc = new javax.swing.JTextField();
        casellaNaixement = new javax.swing.JTextField();
        opcioMasculi = new javax.swing.JRadioButton();
        opcioFemeni = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Inserir = new javax.swing.JButton();
        botoModificar = new javax.swing.JButton();
        botoBorrar = new javax.swing.JButton();
        Sortir = new javax.swing.JButton();
        casellaDiners = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("L M Roman Unsl10", 1, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taula.setFont(new java.awt.Font("Lucida Sans", 0, 15)); // NOI18N
        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Procedencia", "Any de Naixement", "Sexe"
            }
        ));
        taula.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taula);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 900, 416));

        casellaNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casellaNomActionPerformed(evt);
            }
        });
        getContentPane().add(casellaNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1111, 300, 110, -1));

        casellaLloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casellaLlocActionPerformed(evt);
            }
        });
        getContentPane().add(casellaLloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1111, 340, 110, -1));

        casellaNaixement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casellaNaixementActionPerformed(evt);
            }
        });
        getContentPane().add(casellaNaixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 380, 110, -1));

        buttonGroup1.add(opcioMasculi);
        opcioMasculi.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        opcioMasculi.setForeground(new java.awt.Color(254, 254, 254));
        opcioMasculi.setText("Masculi");
        opcioMasculi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioMasculiActionPerformed(evt);
            }
        });
        getContentPane().add(opcioMasculi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, -1, -1));

        buttonGroup1.add(opcioFemeni);
        opcioFemeni.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        opcioFemeni.setForeground(new java.awt.Color(254, 254, 254));
        opcioFemeni.setText("Femeni");
        opcioFemeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioFemeniActionPerformed(evt);
            }
        });
        getContentPane().add(opcioFemeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.controlLtHighlight);
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/dj.png")); // NOI18N
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 90, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/002-signs-2.png")); // NOI18N
        jLabel2.setText("Lloc");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/010-time.png")); // NOI18N
        jLabel3.setText("N.Any");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, -1, -1));

        Inserir.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/009-signs.png")); // NOI18N
        Inserir.setText("Inserir");
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });
        getContentPane().add(Inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 110, -1));

        botoModificar.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/008-draw.png")); // NOI18N
        botoModificar.setText("Modificar");
        botoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoModificarActionPerformed(evt);
            }
        });
        getContentPane().add(botoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, -1, -1));

        botoBorrar.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/011-interface.png")); // NOI18N
        botoBorrar.setText("Borrar");
        botoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(botoBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 119, -1));

        Sortir.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/018-arrow-1.png")); // NOI18N
        Sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortirActionPerformed(evt);
            }
        });
        getContentPane().add(Sortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 620, 110, -1));

        casellaDiners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casellaDinersActionPerformed(evt);
            }
        });
        getContentPane().add(casellaDiners, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 480, 110, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/coins (1).png")); // NOI18N
        jLabel4.setText("Diners");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/dj (2).png")); // NOI18N
        jLabel5.setText(" ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/my-icons-collection (2)/png/007-profile-2.png")); // NOI18N
        jLabel6.setText("Genere");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/my-icons-collection (1)/png/015-business.png")); // NOI18N
        jLabel7.setText("Dades");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, 194, 47));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 45)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/logo.png")); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setMaximumSize(new java.awt.Dimension(293, 17));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 863, 103));

        jLabel12.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/Imagem1000000000000000000000.png")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 330, 640));

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/alumne/NetBeansProjects/Projecte/src/projecte/images/chainimage-fondos-de-pantalla-con-movimiento-memes.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -60, 1330, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casellaNaixementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casellaNaixementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casellaNaixementActionPerformed

    private void opcioFemeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioFemeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcioFemeniActionPerformed

    private void casellaLlocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casellaLlocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casellaLlocActionPerformed

    private void opcioMasculiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioMasculiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcioMasculiActionPerformed

    /**
     * Metode el cual atraves de un element seleccionat ens dona els valors adients per cada un
     * @param evt 
     */
    
    private void taulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaMouseClicked
        //actualitzo la fila seleccionada
        filaSel=taula.getSelectedRow();
        
        //mirem si tenim fila seleccionada i mostrem opcions per defecte en cas qua no es aixi
        if(filaSel==-1){
            botoBorrar.setEnabled(false);
            botoModificar.setEnabled(false);
            
            casellaNom.setText("");
            casellaLloc.setText("");
            casellaNaixement.setText("");
            opcioMasculi.setSelected(true);
        }
        else{
            //En cas de teni fila seleccionada mostres a cada una de les caselles el seu valor actualitzat
            botoBorrar.setEnabled(true);
            botoModificar.setEnabled(true);
        
            casellaNom.setText((String)taula.getValueAt(filaSel,1));
            casellaLloc.setText((String)taula.getValueAt(filaSel,2));
            casellaNaixement.setText(String.valueOf(taula.getValueAt(filaSel,3)));//per als nombres pasem el value of
            //canviem el parametre passat atraves de l'string masculi a opcio masculi o femeni
            if(taula.getValueAt(filaSel,4).equals(MASCULI))
                opcioMasculi.setSelected(true);
            else opcioFemeni.setSelected(true);
            
            casellaDiners.setText(String.valueOf(taula.getValueAt(filaSel,5)));
        }
        
    }//GEN-LAST:event_taulaMouseClicked
    /**
     * Metode que ens indica si les dades son correctes, o si no ho son
     * @param evt 
     */
    
    private boolean dadesCorrectes(){
        try {
            casellaNom.getText().trim().charAt(0);
            //if(casellaNom.getText().trim().equals("")) throw new StringIndexOutOfBoundsException();
            Integer.valueOf(casellaNaixement.getText());
            Double.valueOf(casellaDiners.getText());
        } catch (StringIndexOutOfBoundsException|NumberFormatException e) {
            return false;
        }  
        return true;
    }
    /**
     * Metode el qual ens deixa modificar o no un dj una vegada inserit
     * @param evt 
     */
    private void botoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoModificarActionPerformed
        
        //Mirem si les dades son correctes avans de fer res,Sino ho son mostrem una finestra amb un missatge 
        if(!dadesCorrectes()){
            
            JOptionPane.showMessageDialog(this,"Dades de les caselles incorrectes");
            return;
        }
        //Obtenim index de l'arrai apartir del valor de la columna 0
        int iArray=(int)taula.getValueAt(filaSel,0);
        Dj[] array=Projecte.getArray();
        
        //carreguem cada una de les caselles de el array 
        array[iArray].setNom(casellaNom.getText().trim());
        array[iArray].setLloc(casellaLloc.getText().trim());
        array[iArray].setNaixement(Integer.valueOf(casellaNaixement.getText()));
        array[iArray].setHome(opcioMasculi.isSelected());
        array[iArray].setDiners(Double.valueOf(casellaDiners.getText()));

        //actualitzem la taula
        GUI_UF3.carregaTaula(new String[]{"Fila","Nom", "Lloc","Naixement","Home","Diners"}, 
                transformaDades(Projecte.getArray())
                , taula);
        JOptionPane.showMessageDialog(this,"Dades modificades");
    }//GEN-LAST:event_botoModificarActionPerformed

    private void casellaNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casellaNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casellaNomActionPerformed

    private void casellaDinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casellaDinersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casellaDinersActionPerformed

    /**
     * Metode el qual ens permet inserir un nou element dintr el array de dj
     * @param evt 
     */
    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed
        // Carreguem el array de dj
        Dj[] array=Projecte.getArray();
        
        //comprovem que les dades pasades son correctes dintre els parametres establerts
        if(!dadesCorrectes()){
            JOptionPane.showMessageDialog(this,"Dades de les caselles incorrectes, insereix dades");
            return;
        }

        /**
         * comprovem que per inserir un nou dj tanim espai suficient dintre el arrray per tal de
         * poder inserir un de nou
         */
        
            try {
                    //carreguem una nova entrada introduida per l'usuari
                    array[primeraCasellaBuida].setNom(casellaNom.getText().trim());
                    array[primeraCasellaBuida].setLloc(casellaLloc.getText().trim());
                    array[primeraCasellaBuida].setNaixement(Integer.valueOf(casellaNaixement.getText()));
                    array[primeraCasellaBuida].setHome(opcioMasculi.isSelected());
                    array[primeraCasellaBuida].setDiners(Double.valueOf(casellaDiners.getText()));
                    array[primeraCasellaBuida].setOmplit(true);
                    primeraCasellaBuida++;
                    JOptionPane.showMessageDialog(this,"Nou registre inserit");
            } catch (ArrayIndexOutOfBoundsException e) {
                   
                   //mirem si tenim espai dintre el array,sino en motra el seguent missatge i ens diu si volem sorti o continua sense guardar res
                   Object [] opciones ={"Si","No"};
                   
                   //motrem missatge per tal de informar a l'usari que quina opcio vol continuar
                int eleccion = JOptionPane.showOptionDialog(rootPane,"Atenció, no caben mes dj en memoria. Si continues no es guardara el inserit. Vols continuar(N) o vols sortir (S)?:","Informacio"
                 ,JOptionPane.YES_NO_OPTION,
                 //mpsttrem com ocpio predeterminada el no 
                 JOptionPane.QUESTION_MESSAGE,null,opciones,"No");
                 //segons el seleccionat, ho be no fem res o be sortim de el projecte
                if (eleccion == JOptionPane.NO_OPTION)
                    {
                      System.exit(0);
                    }else{
                     System.out.println("");
                    }
            //si ens sorgueix cualsevol altre error mostrem el seguent missatge
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Error greu contacta amb l'administrador");}
    
            //carreguem la taula altre com per actualitzar el nou dj
     GUI_UF3.carregaTaula(new String[]{"Fila","Nom", "Lloc","Naixement","Home","Diners"}, 
                transformaDades(Projecte.getArray())
                , taula);
                  
    }//GEN-LAST:event_InserirActionPerformed

    private void SortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortirActionPerformed
        //seleccionem la opcio sortir en cas que ens tanquin per la opcio sortir
        projecte.Projecte.sortir();
    }//GEN-LAST:event_SortirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //seleccionem la opcio sortir en cas que ens tanquin per la creu de la finestra
                projecte.Projecte.sortir();
    }//GEN-LAST:event_formWindowClosing
    /**
     * Carreguem metode borrar per tal de poder borrar o no un dj de l'array
     * @param evt 
     */
    private void botoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoBorrarActionPerformed
        
        //passem model predeterminat de la nostra taula
        DefaultTableModel taula1 = (DefaultTableModel) taula.getModel();
        
        //carreguem el array de dj
        Dj[] array=Projecte.getArray();
        
        //borrem atraves de la fila seleccionada
        filaSel=taula.getSelectedRow();
        int [] rows = taula.getSelectedRows(); 
        Arrays.sort(rows);
        
        //advertim que seleccioni una fila el usuari en cas que no haigui seleciionat res
        if (filaSel==-1){     
                JOptionPane.showMessageDialog(null,"Selecciona una fila"); 
        }else{
        
        //atraves la poscio establerta,seleccionada ateriorment recorrem l'array i borem la posicio seleccionada
        for (int i=rows.length-1; i>=0; i--) { 
            taula1.removeRow(rows[i]);}
        
        array[filaSel].setNom(casellaNom.getText().trim());
        array[filaSel].setLloc(casellaLloc.getText().trim());
        array[filaSel].setNaixement(Integer.valueOf(casellaNaixement.getText()));
        array[filaSel].setHome(opcioMasculi.isSelected());
        array[filaSel].setDiners(Double.valueOf(casellaDiners.getText()));
        array[filaSel].setOmplit(false);
        
        //Descrementem en un el nombre de posiscions omplertes en el array
        primeraCasellaBuida--; 

        } 
        //tornem a carregar la taula per guardar els canvis
         GUI_UF3.carregaTaula(new String[]{"Fila","Nom", "Lloc","Naixement","Home","Diners"}, 
         transformaDades(Projecte.getArray())
         , taula);
    }//GEN-LAST:event_botoBorrarActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /**En primer lloc carreguem finestra de inici avans de mostrar el projecte
         * ,indiquem el temps de durarada de aquesta i la execusio de aquesta
         */
        finestrabenvinguda f = new finestrabenvinguda(); 
        f.setVisible (true);
        try {
            Thread.sleep(6* 900);
        }catch (Exception e) {
                    e.printStackTrace();
                }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inserir;
    private javax.swing.JButton Sortir;
    private javax.swing.JButton botoBorrar;
    private javax.swing.JButton botoModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField casellaDiners;
    private javax.swing.JTextField casellaLloc;
    private javax.swing.JTextField casellaNaixement;
    private javax.swing.JTextField casellaNom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcioFemeni;
    private javax.swing.JRadioButton opcioMasculi;
    private javax.swing.JTable taula;
    // End of variables declaration//GEN-END:variables
}
